### ISSUE TITLE
Dev Investigation - Terraform vs ARM templates

### ISSUE THREAD

**Issue by namitms** [Azure-Samples/modern-data-warehouse-dataops#155]
Do a comparative study between Terraforms and ARM templates in terms of capability to deploy Azure Databricks 

# Open questions:
- Is there a supported Terraform provider for ADB?
- What are the advantages / disadvantages of using Terrform or ARM 

# Acceptance criteria 
* Inferences drawn out of the technology comparison between Terraforms and ARM templates with respect to deploying ADB (for requirements captured in issues: #145, #146, #147)

# Definition of done
* Documented inferences of technology comparison

**Comment by xinsnake** [comment]
Confirm if it is from DatabricksLabs??

**Comment by tomomi-code** [comment]
### Comparison

**ARM Templates**
- Azure specific
- Get the latest Azure resources as they are released
- Does not maintain a state file
- Written in JSON
- Does not have a Destroy/Cleanup command

**Terraform**
- Supports multiple cloud providers and on-prem resources
- Can lag behind when new Azure resources are released
- Relies on a state file that must be maintained
- Written in HCL, a custom DSL from Hashicorp
- Able to clean up/destroy resources

**Comment by tomomi-code** [comment]
>Is there a supported Terraform provider for ADB?

[Here](https://dev.azure.com/tosakoAus/_git/Terraform) is the basic terraform for ADB. As you can see, it's working well.
![image](https://user-images.githubusercontent.com/53926778/110705483-92fa4c80-824a-11eb-9902-8076a745aa18.png)

>Confirm if it is from DatabricksLabs??

If you go to [this DataBricksLab document](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#authenticating-with-azure-service-principal), it also suggests using `azurerm` so that I think there is no problem to use `azurerm` for provisioning DataBricks on Azure.

**Comment by xinsnake** [comment]
Documentation to be written and leaving it to the team to decide where it goes.

**Comment by tomomi-code** [comment]
I added the investigation result here. So please review it and if it looks good, I will close this task, thanks.
https://microsoft.sharepoint.com/:o:/t/CSEFTEFY19/EiSH87FccHRNq2ocCfCzhjIB4ZuRAHOe7PnWI_a2dZs-JQ?e=ecFldy
