### ISSUE TITLE
AZ Logins attached to multiple Tenants tries to authenticate to all.

### ISSUE THREAD

**Issue by bsherwin** [Azure-Samples/modern-data-warehouse-dataops#685]
Consider adding AD Tenant to environment vars and doing `az login --tenant TENANT_ID` to explicitly login to a tenant.

DOD
- Make the login/tenant selection consistent with other MDE Samples
- Documentation update or script update to explicitly select tenant for sample deployment.

**Comment by ydaponte** [comment]
@bsherwin - is this issue a duplication of this one: https://github.com/orgs/Azure-Samples/projects/66/views/1?pane=issue&itemId=81998304&issue=Azure-Samples%7Cmodern-data-warehouse-dataops%7C642 ?

**Comment by bsherwin** [comment]
No, I don't think so. I think this issue is about being sure we are using a specific subscription. I think 642 is about how the scope is being interpreted (incorrectly interpreting scope as path relative from the shell).

**Comment by bsherwin** [comment]
Handing off to @thesqlpro (Ayman)

**Comment by ydaponte** [comment]
@thesqlpro - I needed to revert the changes done in https://github.com/Azure-Samples/modern-data-warehouse-dataops/pull/890 with this PR: https://github.com/Azure-Samples/modern-data-warehouse-dataops/pull/907, because the changes were done in different repositories. The changes to the readme were done in the Single Tech Sample of the CICD Fabric and the changes in the script were done in the E2E Databricks sample. So I've rolled back the changes and you can re-worked it when you are back from your time off.
